import type { WorkDescription } from './types'

import soundvis01 from '../resources/small/soundvis_01.JPG'
import soundvis02 from '../resources/small/soundvis_02.JPG'
import soundvis03 from '../resources/small/soundvis_03.JPG'
import shape01 from '../resources/small/shape_01.png'
import shape02 from '../resources/small/shape_02.png'
import shape03 from '../resources/small/shape_03.png'
import shape04 from '../resources/small/shape_04.png'
import random01 from '../resources/small/random-01.jpg'
import random02 from '../resources/small/random-02.jpg'
import random03 from '../resources/small/random-03.jpg'
import master01 from '../resources/small/masterthesis_01.jpg'
import master02 from '../resources/small/masterthesis_02.jpg'
import master03 from '../resources/small/masterthesis_03.jpg'
import master04 from '../resources/small/masterthesis_04.jpg'

const generativeArt: WorkDescription = {
  category: {
    name: '[ generative art ]',
    description: "I'm interested in pattern, noise and form generated by computer algorithm.",
  },
  project: [
    {
      title: '[ SOUND VISUALIZATION ]',
      containerColumn: '49% 40%',
      maxResourceWidth: '48%',
      tools: 'Supervisor: Prof. David Hall (IDAS Korea)  —  Tool: Processing, Maya, Pepakura',
      main_image: {
        image: soundvis01,
        caption: 'Sound visualization in 3D sculpture',
      },
      description:
        'Sound is a crucial source of sensory information for our perception of the external world. While we primarily listen to sound through our ears, what if we could also feel, see, and touch this intangible energy? I am investigating how the brain interprets sound when it is transformed into other mediums. Does this enhance the listening experience or detract from it? To explore this, I employ processing for sound analysis, Maya for 3D object creation, and a laser cutter for paper cutting.',
      resources: [
        { image: soundvis03, text: 'Sound visualization in 3D sculpture' },
        { image: soundvis02, text: 'Sound visualization made of Newspaper' },
      ],
    },
    {
      title: '[ GENERATIVE SHAPES ]',
      containerColumn: '83% 20%',
      maxResourceWidth: '20%',
      tools: 'Tool: openFrameworks',
      main_image: null,
      description:
        "This project expresses the essence of people's names. Our names hold memories, identities, and joy, and are unique to us. Using openFrameworks, I created a shape generator that analyzes a person's name and generates distinct shapes related to it. The first letter serves as the key value for the overall color scheme, while the other letters influence additional visual effects.",
      resources: [
        { image: shape01 },
        { image: shape03 },
        { image: shape02 },
        { image: shape04 },
      ],
    },
    {
      title: '[ BEAUTY OF RANDOMNESS ]',
      containerColumn: '83% 20%',
      maxResourceWidth: '30%',
      tools: 'Tool: Processing and Shader',
      main_image: null,
      description:
        'I am eager to develop an algorithm for a brush and natural color composition. The beauty of randomness makes each render a thrilling moment to see.',
      resources: [
        { image: random01 },
        { image: random02 },
        { image: random03 },
      ],
    },
    {
      title: '[ SEEING MUSIC ]',
      containerColumn: '83% 20%',
      maxResourceWidth: '20%',
      tools:
        'Supervisor: Matti Niinimäki (Aalto University)  —  Advisor: Nuno Correia (University of Greenwich)  —  Tool: Processing',
      main_image: null,
      description:
        'Music and visual art are integral to our daily lives, influencing our emotions through their sensory experiences. This thesis explores the connection between music and generative art, specifically converting music into visual artwork through a colour theme linked to musical emotion. The project is based on an emotional model of arousal and valence and demonstrates how colour impacts our emotions. The thesis details the process of retrieving musical information, including arousal and valence, and demonstrates the implementation of software that integrates musical emotion and characteristics like frequency analysis. The result is a generative artwork that can be applied to various daily life products.',
      resources: [
        { image: master01 },
        { image: master03 },
        { image: master02 },
        { image: master04 },
      ],
    },
    {
      title: '[ DRAWING MACHINE ]',
      containerColumn: '65% 35%',
      maxResourceWidth: '40%',
      tools: 'Supervisor: Prof. David Hall (IDAS Korea)  —  Tool: Arduino, Stepper motors, Sensors, Servo motors',
      main_image: { movie: 'mVPDrrjWDYY', height: '200%' },
      description:
        'This project introduces a new type of drawing machine that can create curves and lines with a natural flow. Using Morse code, a well-known method of communication, the drawing machine will convert messages, such as "LOVE," into a visual representation. This allows the machine to express messages in a unique and creative way.',
    },
  ],
}

export default generativeArt
